"""propiedad porciones

Revision ID: 1c4aceac3cb5
Revises: a1ceb753c0c6
Create Date: 2025-02-06 19:55:53.680506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4aceac3cb5'
down_revision = 'a1ceb753c0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porciones', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.drop_column('porciones')

    # ### end Alembic commands ###
