"""modelo para ingredientes

Revision ID: 232084c203ad
Revises: 8ed57f5dcaa9
Create Date: 2025-01-14 19:20:30.909815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '232084c203ad'
down_revision = '8ed57f5dcaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plato_ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('unidad', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.drop_column('ingredientes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredientes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.drop_table('plato_ingredientes')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
