"""modificacion de modelo User

Revision ID: 45959f70ed6e
Revises: f8b25e43a942
Create Date: 2025-01-31 15:29:15.737293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45959f70ed6e'
down_revision = 'f8b25e43a942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
