"""inicio

Revision ID: 5d850995d839
Revises: 
Create Date: 2025-01-03 16:12:05.301216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d850995d839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensaladas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ingredientes', sa.Text(), nullable=True),
    sa.Column('preparacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combinaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=False),
    sa.Column('ensalada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ensalada_id'], ['ensaladas.id'], ),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combinaciones')
    op.drop_table('platos')
    op.drop_table('ensaladas')
    # ### end Alembic commands ###
