"""user_id en platoIngrediente

Revision ID: 67942cf1175e
Revises: 1471f39711a7
Create Date: 2025-02-01 17:30:08.423928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67942cf1175e'
down_revision = '1471f39711a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
