"""tabla unidades

Revision ID: 724c81f6d90e
Revises: 232084c203ad
Create Date: 2025-01-14 21:36:19.217942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724c81f6d90e'
down_revision = '232084c203ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidades', ['unidad_id'], ['id'])
        batch_op.drop_column('unidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidad_id')

    op.drop_table('unidades')
    # ### end Alembic commands ###
