"""users ondelete CASCADE

Revision ID: a1ceb753c0c6
Revises: 67942cf1175e
Create Date: 2025-02-01 17:37:56.482891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ceb753c0c6'
down_revision = '67942cf1175e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.drop_constraint('combinaciones_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint('plato_ingredientes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato_ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('plato_ingredientes_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('combinaciones_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
