"""fila para imagenes en platos

Revision ID: a82fced6e12f
Revises: fb53990ace2f
Create Date: 2025-01-03 23:07:39.786864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82fced6e12f'
down_revision = 'fb53990ace2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
