"""tabla combinacion ahora con campo 'dia'

Revision ID: cea8bfd62996
Revises: 5d850995d839
Create Date: 2025-01-03 17:35:01.790391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea8bfd62996'
down_revision = '5d850995d839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia', sa.String(length=20), nullable=True))
        batch_op.alter_column('plato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ensalada_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.alter_column('ensalada_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('plato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('dia')

    # ### end Alembic commands ###
