"""nueva tabla CARBOHIDRATOS y columna FECHA para tabla COMBINACIONES

Revision ID: e542b17842d2
Revises: a82fced6e12f
Create Date: 2025-01-04 15:32:00.284015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e542b17842d2'
down_revision = 'a82fced6e12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbohidratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plato_id'], ['platos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combinaciones', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    op.drop_table('carbohidratos')
    # ### end Alembic commands ###
