"""cambiando ingredientes a JSON

Revision ID: fb53990ace2f
Revises: cea8bfd62996
Create Date: 2025-01-03 21:19:45.764188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb53990ace2f'
down_revision = 'cea8bfd62996'
branch_labels = None
depends_on = None

def upgrade():
    op.execute("""
        ALTER TABLE platos 
        ALTER COLUMN ingredientes 
        TYPE JSON 
        USING CASE
            WHEN ingredientes ~ '^\s*[\[{].*[\]}]\s*$' THEN ingredientes::json  -- Validar si es JSON
            ELSE '[]'::json  -- Si no es JSON, asignar un valor por defecto (array vacío)
        END
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE platos ALTER COLUMN ingredientes TYPE TEXT USING ingredientes::text')

    # ### end Alembic commands ###


    # ### end Alembic commands ###
